version: '3'

services:
  jenkins:
    privileged: true
    build: .
    ports:
      - 50000:50000
      - 8080:8080
    environment:
      USER_CHOCOLATEEN_PASSWORD: "${USER_CHOCOLATEEN_PASSWORD}"
      USER_VAUGIE_G_PASSWORD: "${USER_VAUGIE_G_PASSWORD}"
      USER_I_DONT_KNOW_PASSWORD: "${USER_I_DONT_KNOW_PASSWORD}"
      USER_NASSO_PASSWORD: "${USER_NASSO_PASSWORD}"